site_name: "ChatGPT"
theme:
  name: material
nav:
  - Inicio: index.md
  - "LLMs": 1_LLM/index.md
  - "Ingeniería de Prompts": 2_IP/index.md
  - "Ingeniería de Contexto": 3_IC/index.md
  - "Programación": 4_Programación/index.md
  - "Trabajo Práctico": 5_Trabajo Práctico/index.md
